version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: obrail_datamart_pg
    environment:
      POSTGRES_DB: datamart_co2
      POSTGRES_USER: obrail
      POSTGRES_PASSWORD: obrail123
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
